### ISSUE TITLE
A problem about target_acc ?

### ISSUE THREAD

**Issue by lllzzz3** [mlvlab/CAF#1]
why target_acc = 2*(x_start - noise) - 2*pred_vel in the pipeline_caf.py ?
I think change it into target_acc = 2*(x_start - noise) - 2*target_vel maybe a little better. Because in a simple thought,  'target_vel' is more precise than pred_vel.
I am glad to receive your reply, thank you.

**Comment by DogyunPark** [comment]
Thanks for your interest in our paper.
 
The current implementation in the code aligns with the methodology described in our paper.

As outlined in Eq.5 in our paper, the acceleration model is designed to learn the appropriate flow for the given initial velocity.
By using the predicted initial velocity (pred_vel), the acceleration model adjusts for any potential estimation errors in the velocity prediction. This mechanism allows the acceleration model to guide the flow toward the correct output, ensuring robustness even when the initial velocity is not perfectly accurate.

I hope this clarifies the rationale behind our approach. Let me know if you have further questions!
